export interface VedaData {
  id: string
  tipoVeda: "Permanente" | "Temporal Fija" | "Temporal Variable"
  pesqueria: string
  nombreCientifico: string
  region: string
  zona: "Océano Pacífico" | "Golfo de México y Mar Caribe" | "Aguas continentales" | "Nacional"
  fechaInicio1: string
  fechaTermino1: string
  fechaInicio2: string
  fechaTermino2: string
  fechaInicio3: string
  fechaTermino3: string
  enlaceDOF: string
  fechaPublicacion: string
  nombreAcuerdo: string
  status: "Activa" | "Inactiva"
}

// Interface for calendar component
export interface Veda {
  id: string
  tipoVeda: "Permanente" | "Temporal Fija" | "Temporal Variable"
  pesqueria: string
  nombreCientifico: string
  region: string
  zona: "Océanos Pacífico" | "Golfo de México y Mar Caribe" | "Aguas continentales" | "Nacional"
  fechaInicio1: string
  fechaTermino1: string
  fechaInicio2: string
  fechaTermino2: string
  fechaInicio3: string
  fechaTermino3: string
  estado: "activa" | "inactiva"
}

export const vedasData: VedaData[] = [
  // Vedas Permanentes
  {
    "id": "1",
    "tipoVeda": "Permanente",
    "pesqueria": "Ballena gris",
    "nombreCientifico": "Eschrichtius robustus",
    "region": "BC y BCS (Costa Occidental)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/normasOficiales/4254/semarnat/semarnat.htm",
    "fechaPublicacion": "30/12/10",
    "nombreAcuerdo": "NOM-059-SEMARNAT-2010, Protección ambiental-Especies nativas de México de flora y fauna silvestres",
    "status": "Activa"
  },
  {
    "id": "2",
    "tipoVeda": "Permanente",
    "pesqueria": "Ballena jorobada",
    "nombreCientifico": "Megaptera novaeangliae",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/normasOficiales/4254/semarnat/semarnat.htm",
    "fechaPublicacion": "30/12/10",
    "nombreAcuerdo": "NOM-059-SEMARNAT-2010, Protección ambiental-Especies nativas de México de flora y fauna silvestres",
    "status": "Activa"
  },
  {
    "id": "3",
    "tipoVeda": "Permanente",
    "pesqueria": "Ballena azul",
    "nombreCientifico": "Balaenoptera musculus",
    "region": "BC y BCS (Costa Occidental)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/normasOficiales/4254/semarnat/semarnat.htm",
    "fechaPublicacion": "30/12/10",
    "nombreAcuerdo": "NOM-059-SEMARNAT-2010, Protección ambiental-Especies nativas de México de flora y fauna silvestres",
    "status": "Activa"
  },
  {
    "id": "4",
    "tipoVeda": "Permanente",
    "pesqueria": "Rorcual común",
    "nombreCientifico": "Balaenoptera physalus",
    "region": "Golfo de California",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/normasOficiales/4254/semarnat/semarnat.htm",
    "fechaPublicacion": "30/12/10",
    "nombreAcuerdo": "NOM-059-SEMARNAT-2010, Protección ambiental-Especies nativas de México de flora y fauna silvestres",
    "status": "Activa"
  },
  {
    "id": "5",
    "tipoVeda": "Permanente",
    "pesqueria": "Camarón rosado",
    "nombreCientifico": "Farfantepenaeus duorarum",
    "region": "Campeche-Belice (0-15 millas)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4888578&fecha=30/04/1999",
    "fechaPublicacion": "30/04/99",
    "nombreAcuerdo": "AVISO por el que se modifica la veda establecida en el diverso publicado el 16 de marzo de 1994",
    "status": "Activa"
  },
  {
    "id": "6",
    "tipoVeda": "Permanente",
    "pesqueria": "Camarón café",
    "nombreCientifico": "Farfantepenaeus aztecus",
    "region": "Campeche-Belice (0-15 millas)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4888578&fecha=30/04/1999",
    "fechaPublicacion": "30/04/99",
    "nombreAcuerdo": "AVISO por el que se modifica la veda establecida en el diverso publicado el 16 de marzo de 1994",
    "status": "Activa"
  },
  {
    "id": "7",
    "tipoVeda": "Permanente",
    "pesqueria": "Camarón blanco",
    "nombreCientifico": "Litopenaeus setiferus",
    "region": "Campeche-Belice (0-15 millas)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4888578&fecha=30/04/1999",
    "fechaPublicacion": "30/04/99",
    "nombreAcuerdo": "AVISO por el que se modifica la veda establecida en el diverso publicado el 16 de marzo de 1994",
    "status": "Activa"
  },
  {
    "id": "8",
    "tipoVeda": "Permanente",
    "pesqueria": "Camarón rojo",
    "nombreCientifico": "Farfantepenaeus brasiliensis",
    "region": "Laguna de Términos, Campeche",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",    
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4887135&fecha=04/11/1996",
    "fechaPublicacion": "04/11/96",
    "nombreAcuerdo": "AVISO por el que se modifica la veda establecida en el diverso publicado el 16 de marzo de 1994",
    "status": "Activa"
  },
  {
    "id": "9",
    "tipoVeda": "Permanente",
    "pesqueria": "Camarón sintético",
    "nombreCientifico": "Trachypenaeus similis",
    "region": "Laguna de Términos, Campeche",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4887135&fecha=04/11/1996",
    "fechaPublicacion": "04/11/96",
    "nombreAcuerdo": "AVISO por el que se modifica la veda establecida en el diverso publicado el 16 de marzo de 1994",
    "status": "Activa"
  },
  {
    "id": "10",
    "tipoVeda": "Permanente",
    "pesqueria": "Camarón sintético",
    "nombreCientifico": "Trachypenaeus constrictus",
    "region": "Campeche, Quintana Roo, Yucatán (Sistemas lagunares)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4888263&fecha=23/09/1997",
    "fechaPublicacion": "23/09/97",
    "nombreAcuerdo": "AVISO por el que se modifica la veda establecida en el diverso publicado el 16 de marzo de 1994",
    "status": "Activa"
  },
  {
    "id": "11",
    "tipoVeda": "Permanente",
    "pesqueria": "Caracol rosa",
    "nombreCientifico": "Lobatus gigas",
    "region": "Yucatán (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "12",
    "tipoVeda": "Permanente",
    "pesqueria": "Caracol lanceta",
    "nombreCientifico": "Strombus costatus",
    "region": "Yucatán (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "13",
    "tipoVeda": "Permanente",
    "pesqueria": "Caracol tomburro",
    "nombreCientifico": "Xancus sp",
    "region": "Yucatán (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "14",
    "tipoVeda": "Permanente",
    "pesqueria": "Caracol chirita",
    "nombreCientifico": "Busycon sp",
    "region": "Yucatán (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "15",
    "tipoVeda": "Permanente",
    "pesqueria": "Caracol chactel",
    "nombreCientifico": "Pleuroploca gigantea",
    "region": "Yucatán (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "16",
    "tipoVeda": "Permanente",
    "pesqueria": "Coral blando",
    "nombreCientifico": "Plexaura homomalla",
    "region": "Mar Caribe",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "17",
    "tipoVeda": "Permanente",
    "pesqueria": "Delfín nariz de botella",
    "nombreCientifico": "Tursiops truncatus",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/normasOficiales/4254/semarnat/semarnat.htm",
    "fechaPublicacion": "30/12/10",
    "nombreAcuerdo": "NOM-059-SEMARNAT-2010, Protección ambiental-Especies nativas de México de flora y fauna silvestres",
    "status": "Activa"
  },
  {
    "id": "18",
    "tipoVeda": "Permanente",
    "pesqueria": "Elefante marino",
    "nombreCientifico": "Macrorhinus angustirostris",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "19",
    "tipoVeda": "Permanente",
    "pesqueria": "Foca fina",
    "nombreCientifico": "Arctocephalus townsendii",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "20",
    "tipoVeda": "Permanente",
    "pesqueria": "Manatí",
    "nombreCientifico": "Trichechus manatus",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "21",
    "tipoVeda": "Permanente",
    "pesqueria": "Manjúa (alevines)",
    "nombreCientifico": "Diferentes especies",
    "region": "Coahuila (Aguas interiores)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "22",
    "tipoVeda": "Permanente",
    "pesqueria": "Mantarraya gigante",
    "nombreCientifico": "Manta birostris",
    "region": "Revillagigedo, Guadalupe (12 millas náuticas)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868397&fecha=25/03/1994",
    "fechaPublicacion": "25/03/94",
    "nombreAcuerdo": "AVISO por el que se establece veda permanente para todas las especies de mantarraya",
    "status": "Activa"
  },
  {
    "id": "23",
    "tipoVeda": "Permanente",
    "pesqueria": "Mantarraya japonesa",
    "nombreCientifico": "Mobula japanica",
    "region": "Revillagigedo, Guadalupe (12 millas náuticas)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868397&fecha=25/03/1994",
    "fechaPublicacion": "25/03/94",
    "nombreAcuerdo": "AVISO por el que se establece veda permanente para todas las especies de mantarraya",
    "status": "Activa"
  },
  {
    "id": "24",
    "tipoVeda": "Permanente",
    "pesqueria": "Mantarraya de Lucas",
    "nombreCientifico": "Mobula lucasana",
    "region": "Revillagigedo, Guadalupe (12 millas náuticas)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868397&fecha=25/03/1994",
    "fechaPublicacion": "25/03/94",
    "nombreAcuerdo": "AVISO por el que se establece veda permanente para todas las especies de mantarraya",
    "status": "Activa"
  },
  {
    "id": "25",
    "tipoVeda": "Permanente",
    "pesqueria": "Mantarraya gigante",
    "nombreCientifico": "Manta birostris",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/normasOficiales/3684/conapesca-semarnat/conapesca-semarnat.htm",
    "fechaPublicacion": "14/02/07",
    "nombreAcuerdo": "NOM-029-PESC-2006, Pesca responsable de tiburones y rayas",
    "status": "Activa"
  },
  {
    "id": "26",
    "tipoVeda": "Permanente",
    "pesqueria": "Mantarraya japonesa",
    "nombreCientifico": "Mobula japanica",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/normasOficiales/3684/conapesca-semarnat/conapesca-semarnat.htm",
    "fechaPublicacion": "14/02/07",
    "nombreAcuerdo": "NOM-029-PESC-2006, Pesca responsable de tiburones y rayas",
    "status": "Activa"
  },
  {
    "id": "27",
    "tipoVeda": "Permanente",
    "pesqueria": "Mantarraya de Thurston",
    "nombreCientifico": "Mobula thurstoni",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/normasOficiales/3684/conapesca-semarnat/conapesca-semarnat.htm",
    "fechaPublicacion": "14/02/07",
    "nombreAcuerdo": "NOM-029-PESC-2006, Pesca responsable de tiburones y rayas",
    "status": "Activa"
  },
  {
    "id": "28",
    "tipoVeda": "Permanente",
    "pesqueria": "Mantarraya pigmea",
    "nombreCientifico": "Mobula munkiana",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/normasOficiales/3684/conapesca-semarnat/conapesca-semarnat.htm",
    "fechaPublicacion": "14/02/07",
    "nombreAcuerdo": "NOM-029-PESC-2006, Pesca responsable de tiburones y rayas",
    "status": "Activa"
  },
  {
    "id": "29",
    "tipoVeda": "Permanente",
    "pesqueria": "Pepino café",
    "nombreCientifico": "Isostichopus badionotus",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5518748&fecha=06/04/2018",
    "fechaPublicacion": "06/04/18",
    "nombreAcuerdo": "ACUERDO por el que se establece veda permanente para todas las especies de pepino de mar",
    "status": "Activa"
  },
  {
    "id": "30",
    "tipoVeda": "Permanente",
    "pesqueria": "Pepino negro",
    "nombreCientifico": "Holothuria floridana",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5518748&fecha=06/04/2018",
    "fechaPublicacion": "06/04/18",
    "nombreAcuerdo": "ACUERDO por el que se establece veda permanente para todas las especies de pepino de mar",
    "status": "Activa"
  },
  {
    "id": "31",
    "tipoVeda": "Permanente",
    "pesqueria": "Pepino blanco",
    "nombreCientifico": "Astichopus multifidus",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5518748&fecha=06/04/2018",
    "fechaPublicacion": "06/04/18",
    "nombreAcuerdo": "ACUERDO por el que se establece veda permanente para todas las especies de pepino de mar",
    "status": "Activa"
  },
  {
    "id": "32",
    "tipoVeda": "Permanente",
    "pesqueria": "Pepino Michelin",
    "nombreCientifico": "Holothuria mexicana",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5518748&fecha=06/04/2018",
    "fechaPublicacion": "06/04/18",
    "nombreAcuerdo": "ACUERDO por el que se establece veda permanente para todas las especies de pepino de mar",
    "status": "Activa"
  },
  {
    "id": "33",
    "tipoVeda": "Permanente",
    "pesqueria": "Marlín negro",
    "nombreCientifico": "Makaira indica",
    "region": "Zonas A y B (0-50 millas/comercial)",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "34",
    "tipoVeda": "Permanente",
    "pesqueria": "Marlín azul",
    "nombreCientifico": "Makaira nigricans",
    "region": "Zonas A y B (0-50 millas/comercial)",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "35",
    "tipoVeda": "Permanente",
    "pesqueria": "Marlín rayado",
    "nombreCientifico": "Tetrapturus audax",
    "region": "Zonas A y B (0-50 millas/comercial)",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "36",
    "tipoVeda": "Permanente",
    "pesqueria": "Marlín blanco",
    "nombreCientifico": "Tetrapturus albidus",
    "region": "Zonas A y B (0-50 millas/comercial)",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "37",
    "tipoVeda": "Permanente",
    "pesqueria": "Pez aguja corta",
    "nombreCientifico": "Tetrapturus angustirostris",
    "region": "Zonas A y B (0-50 millas/comercial)",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "38",
    "tipoVeda": "Permanente",
    "pesqueria": "Pez vela",
    "nombreCientifico": "Istiophorus platypterus",
    "region": "Zonas A y B (0-50 millas/comercial)",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "39",
    "tipoVeda": "Permanente",
    "pesqueria": "Pez espada",
    "nombreCientifico": "Xiphia gladius",
    "region": "Zonas A y B (0-50 millas/comercial)",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "40",
    "tipoVeda": "Permanente",
    "pesqueria": "Tiburón ballena",
    "nombreCientifico": "Rhincodon typus",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/normasOficiales/3684/conapesca-semarnat/conapesca-semarnat.htm",
    "fechaPublicacion": "14/02/07",
    "nombreAcuerdo": "NOM-029-PESC-2006, Pesca responsable de tiburones y rayas",
    "status": "Activa"
  },
  {
    "id": "41",
    "tipoVeda": "Permanente",
    "pesqueria": "Tiburón peregrino",
    "nombreCientifico": "Cetorhinus maximus",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/normasOficiales/3684/conapesca-semarnat/conapesca-semarnat.htm",
    "fechaPublicacion": "14/02/07",
    "nombreAcuerdo": "NOM-029-PESC-2006, Pesca responsable de tiburones y rayas",
    "status": "Activa"
  },
  {
    "id": "42",
    "tipoVeda": "Permanente",
    "pesqueria": "Tiburón blanco",
    "nombreCientifico": "Carcharodon carcharias",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/normasOficiales/3684/conapesca-semarnat/conapesca-semarnat.htm",
    "fechaPublicacion": "14/02/07",
    "nombreAcuerdo": "NOM-029-PESC-2006, Pesca responsable de tiburones y rayas",
    "status": "Activa"
  },
  {
    "id": "43",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga carey",
    "nombreCientifico": "Eretmochelys imbricata",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "44",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga cahuama",
    "nombreCientifico": "Caretta caretta",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "45",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga lora",
    "nombreCientifico": "Lepidochelys kempii",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "46",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga golfina",
    "nombreCientifico": "Lepidochelys olivacea",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "47",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga laúd",
    "nombreCientifico": "Dermochelys coriacea",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "48",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga prieta",
    "nombreCientifico": "Chelonia agassizi",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "49",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga blanca marina",
    "nombreCientifico": "Chelonia mydas",
    "region": "Nacional",
    "zona": "Nacional",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "50",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga crusilla",
    "nombreCientifico": "Staurotypus salvini",
    "region": "Tabasco, Chiapas, Oaxaca (Aguas interiores)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "51",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga Guao",
    "nombreCientifico": "Staurotypus triporcatus",
    "region": "Veracruz, Tabasco, Campeche, Chiapas, Oaxaca (Aguas interiores)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "52",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga jicotea",
    "nombreCientifico": "Pseudemys scripta ornata",
    "region": "Múltiples estados (Aguas interiores)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "53",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga blanca dulce",
    "nombreCientifico": "Triony ater",
    "region": "Coahuila (Aguas interiores)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "54",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga aplanada",
    "nombreCientifico": "Dermatemys maewi",
    "region": "Múltiples estados sur (Aguas interiores)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "55",
    "tipoVeda": "Permanente",
    "pesqueria": "Tortuga cuatro ciénegas",
    "nombreCientifico": "Terrapene coahuila",
    "region": "Coahuila (Aguas interiores)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  {
    "id": "56",
    "tipoVeda": "Permanente",
    "pesqueria": "Totoaba",
    "nombreCientifico": "Totoaba macdonaldi",
    "region": "Golfo de California",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/94",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda",
    "status": "Activa"
  },
  // Vedas Fijas
  {
    "id": "57",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Abulón",
    "nombreCientifico": "Todas las especies",
    "region": "BC y BCS (Zona I)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-08-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5348479&fecha=13/06/2014",
    "fechaPublicacion": "13/06/2014",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para jaiba",
    "status": "Inactiva"
  },
  {
    "id": "58",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Abulón",
    "nombreCientifico": "Todas las especies",
    "region": "BC y BCS (Zona II)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-09-01",
    "fechaTermino1": "2026-01-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5623156&fecha=07/07/2021",
    "fechaPublicacion": "07/07/2021",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda de abulón establecida en el Aviso publicado el 16 de marzo de 1994"
  },
  {
    "id": "59",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Abulón",
    "nombreCientifico": "Todas las especies",
    "region": "BC y BCS (Zona III)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-09-01",
    "fechaTermino1": "2026-01-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5623156&fecha=07/07/2021",
    "fechaPublicacion": "07/07/2021",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda de abulón establecida en el Aviso publicado el 16 de marzo de 1994"
  },
  {
    "id": "60",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Abulón",
    "nombreCientifico": "Todas las especies",
    "region": "BC y BCS (Zona IV)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-10-01",
    "fechaTermino1": "2026-02-28",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5623156&fecha=07/07/2021",
    "fechaPublicacion": "07/07/2021",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda de abulón establecida en el Aviso publicado el 16 de marzo de 1994"
  },
  {
    "id": "61",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Almeja catarina",
    "nombreCientifico": "Argopecten circularis",
    "region": "BC y BCS (Litoral)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-12-15",
    "fechaTermino1": "2026-03-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "62",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Almeja chocolata",
    "nombreCientifico": "Megapitaria squalida",
    "region": "Sistema Lagunar Altata, Sinaloa",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2022-09-08",
    "fechaTermino1": "2023-09-08",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5664174&fecha=08/09/2022",
    "fechaPublicacion": "08/09/2022",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para la almeja chocolata"
  },
  {
    "id": "63",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Almeja chocolata",
    "nombreCientifico": "Megapitaria squalida",
    "region": "Bahía Magdalena-Almejas, BCS",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-09-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5616476&fecha=16/04/2021",
    "fechaPublicacion": "16/04/2021",
    "nombreAcuerdo": "ACUERDO por el que se modifica el diverso por el que se establece veda temporal para la almeja chocolata"
  },
  {
    "id": "64",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Almeja generosa",
    "nombreCientifico": "Panopea globosa",
    "region": "Bahía Magdalena, BCS",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2026-01-25",
    "fechaTermino1": "2026-04-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5616476&fecha=16/04/2021",
    "fechaPublicacion": "16/04/2021",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para la almeja generosa"
  },
  {
    "id": "65",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Atún aleta amarilla",
    "nombreCientifico": "Thunnus albacares",
    "region": "Océano Pacífico",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-29",
    "fechaTermino1": "2025-10-08",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5651985&fecha=18/05/2022",
    "fechaPublicacion": "18/05/2022",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para las especies de atún"
  },
  {
    "id": "66",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Atún aleta azul",
    "nombreCientifico": "Thunnus orientalis",
    "region": "Océano Pacífico",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-29",
    "fechaTermino1": "2025-10-08",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5651985&fecha=18/05/2022",
    "fechaPublicacion": "18/05/2022",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para las especies de atún"
  },
  {
    "id": "67",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Patudo",
    "nombreCientifico": "Thunnus obesus",
    "region": "Océano Pacífico",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-29",
    "fechaTermino1": "2025-10-08",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5651985&fecha=18/05/2022",
    "fechaPublicacion": "18/05/2022",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para las especies de atún"
  },
  {
    "id": "68",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Barrilete",
    "nombreCientifico": "Katsuwonus pelamis",
    "region": "Océano Pacífico",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-29",
    "fechaTermino1": "2025-10-08",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5651985&fecha=18/05/2022",
    "fechaPublicacion": "18/05/2022",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para las especies de atún"
  },
  {
    "id": "69",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Bagre",
    "nombreCientifico": "Ictalurus dugessi",
    "region": "Lago Chapala, Jalisco y Michoacán",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-08-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5135886&fecha=31/03/2010",
    "fechaPublicacion": "31/03/2010",
    "nombreAcuerdo": "ACUERDO por el que se establece veda para especies de aguas continentales"
  },
  {
    "id": "70",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Bagre",
    "nombreCientifico": "Ictalurus punctatus",
    "region": "Chihuahua (Embalses)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-04-02",
    "fechaTermino1": "2025-06-25",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5135886&fecha=31/03/2010",
    "fechaPublicacion": "31/03/2010",
    "nombreAcuerdo": "ACUERDO por el que se establece veda para especies de aguas continentales"
  },
  {
    "id": "71",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Bagre",
    "nombreCientifico": "Ictalurus furcatus",
    "region": "Chihuahua (Embalses)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-04-02",
    "fechaTermino1": "2025-06-25",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5135886&fecha=31/03/2010",
    "fechaPublicacion": "31/03/2010",
    "nombreAcuerdo": "ACUERDO por el que se establece veda para especies de aguas continentales"
  },
  {
    "id": "72",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Bobo",
    "nombreCientifico": "Joturus spp",
    "region": "Veracruz (Aguas interiores)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-10-01",
    "fechaTermino1": "2025-12-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5135886&fecha=31/03/2010",
    "fechaPublicacion": "31/03/2010",
    "nombreAcuerdo": "ACUERDO por el que se establece veda para especies de aguas continentales"
  },
  {
    "id": "73",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Callo de hacha",
    "nombreCientifico": "Pinna rugosa",
    "region": "Bahía de Kino, Sonora",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-01",
    "fechaTermino1": "2025-11-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5524050&fecha=22/05/2018",
    "fechaPublicacion": "22/05/2018",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para callo de hacha"
  },
  {
    "id": "74",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Callo de hacha",
    "nombreCientifico": "Atrina oldroydii",
    "region": "Bahía de Kino, Sonora",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-01",
    "fechaTermino1": "2025-11-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5524050&fecha=22/05/2018",
    "fechaPublicacion": "22/05/2018",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para callo de hacha"
  },
  {
    "id": "75",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Callo de hacha",
    "nombreCientifico": "Atrina maura",
    "region": "Bahía de Kino, Sonora",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-01",
    "fechaTermino1": "2025-11-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5524050&fecha=22/05/2018",
    "fechaPublicacion": "22/05/2018",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para callo de hacha"
  },
  {
    "id": "76",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Callo de hacha",
    "nombreCientifico": "Atrina tuberculosa",
    "region": "Bahía de Kino, Sonora",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-01",
    "fechaTermino1": "2025-11-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5524050&fecha=22/05/2018",
    "fechaPublicacion": "22/05/2018",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para callo de hacha"
  },
  {
    "id": "77",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Callo de hacha",
    "nombreCientifico": "Pinna rugosa",
    "region": "Bahía Magdalena-Almejas, BCS",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-04-01",
    "fechaTermino1": "2025-07-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5611659&fecha=10/02/2021",
    "fechaPublicacion": "10/02/2021",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para callo de hacha"
  },
  {
    "id": "78",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Callo de hacha",
    "nombreCientifico": "Atrina maura",
    "region": "Bahía Magdalena-Almejas, BCS",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-04-01",
    "fechaTermino1": "2025-07-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5611659&fecha=10/02/2021",
    "fechaPublicacion": "10/02/2021",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para callo de hacha"
  },
  {
    "id": "79",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Caracol rosa",
    "nombreCientifico": "Lobatus gigas",
    "region": "Quintana Roo (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-10-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "80",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Caracol rosa",
    "nombreCientifico": "Lobatus gigas",
    "region": "Banco Chinchorro, Quintana Roo",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2026-02-01",
    "fechaTermino1": "2026-02-28",
    "fechaInicio2": "2025-05-01",
    "fechaTermino2": "2025-11-30",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5491054&fecha=19/07/2017",
    "fechaPublicacion": "19/07/2017",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda para el caracol rosa"
  },
  {
    "id": "81",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Caracoles",
    "nombreCientifico": "Todas las especies",
    "region": "Campeche (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-07-16",
    "fechaTermino1": "2026-03-14",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5020837&fecha=06/05/2008",
    "fechaPublicacion": "06/05/2008",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para especies de caracol"
  },
  {
    "id": "82",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Cangrejo azul",
    "nombreCientifico": "Cardisoma guanhumi",
    "region": "Veracruz (Aguas estuarinas-marinas)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-08-15",
    "fechaTermino1": "2025-09-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5446078&fecha=04/08/2016",
    "fechaPublicacion": "04/08/2016",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para el cangrejo azul"
  },
  {
    "id": "83",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Charal",
    "nombreCientifico": "Chirostoma chapalae",
    "region": "Lago Chapala, Jalisco y Michoacán",
    "zona": "Aguas continentales",
    "fechaInicio1": "2026-03-01",
    "fechaTermino1": "2026-04-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5135886&fecha=31/03/2010",
    "fechaPublicacion": "31/03/2010",
    "nombreAcuerdo": "ACUERDO por el que se establece veda para especies de aguas continentales"
  },
  {
    "id": "84",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Curvina golfina",
    "nombreCientifico": "Cynoscion othonopterus",
    "region": "Alto Golfo-Delta Colorado",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-08-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5096659&fecha=25/08/2005",
    "fechaPublicacion": "25/08/2005",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para la curvina golfina"
  },
  {
    "id": "85",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Erizo rojo",
    "nombreCientifico": "Strongylocentrotus franciscanus",
    "region": "Costa oeste BC",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2026-03-01",
    "fechaTermino1": "2026-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "86",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Jaiba azul",
    "nombreCientifico": "Callinectes arcuatus",
    "region": "Sonora y Sinaloa (Litorales)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5348479&fecha=13/06/2014",
    "fechaPublicacion": "13/06/2014",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para jaiba"
  },
  {
    "id": "87",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Jaiba café",
    "nombreCientifico": "Callinectes bellicosus",
    "region": "Sonora y Sinaloa (Litorales)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5348479&fecha=13/06/2014",
    "fechaPublicacion": "13/06/2014",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para jaiba"
  },
  {
    "id": "88",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Jaiba gigante",
    "nombreCientifico": "Callinectes toxotes",
    "region": "Sonora y Sinaloa (Litorales)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5348479&fecha=13/06/2014",
    "fechaPublicacion": "13/06/2014",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para jaiba"
  },
  {
    "id": "89",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta azul",
    "nombreCientifico": "Panulirus inflatus",
    "region": "BC y BCS (Costa Occidental I)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2026-02-16",
    "fechaTermino1": "2025-09-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5096857&fecha=31/08/2005",
    "fechaPublicacion": "31/08/2005",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para langosta"
  },
  {
    "id": "90",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta verde",
    "nombreCientifico": "Panulirus gracilis",
    "region": "BC y BCS (Costa Occidental I)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2026-02-16",
    "fechaTermino1": "2025-09-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5096857&fecha=31/08/2005",
    "fechaPublicacion": "31/08/2005",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para langosta"
  },
  {
    "id": "91",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta roja",
    "nombreCientifico": "Panulirus interruptus",
    "region": "BC y BCS (Costa Occidental I)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2026-02-16",
    "fechaTermino1": "2025-09-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5096857&fecha=31/08/2005",
    "fechaPublicacion": "31/08/2005",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para langosta"
  },
  {
    "id": "92",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta azul",
    "nombreCientifico": "Panulirus inflatus",
    "region": "BC y BCS (Costa Occidental II)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2026-03-01",
    "fechaTermino1": "2025-09-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5703179&fecha=26/09/2023",
    "fechaPublicacion": "26/09/2023",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda de langosta en la zona II"
  },
  {
    "id": "93",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta verde",
    "nombreCientifico": "Panulirus gracilis",
    "region": "BC y BCS (Costa Occidental II)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2026-03-01",
    "fechaTermino1": "2025-09-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5703179&fecha=26/09/2023",
    "fechaPublicacion": "26/09/2023",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda de langosta en la zona II"
  },
  {
    "id": "94",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta roja",
    "nombreCientifico": "Panulirus interruptus",
    "region": "BC y BCS (Costa Occidental II)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2026-03-01",
    "fechaTermino1": "2025-09-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5703179&fecha=26/09/2023",
    "fechaPublicacion": "26/09/2023",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda de langosta en la zona II"
  },
  {
    "id": "95",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta azul",
    "nombreCientifico": "Panulirus inflatus",
    "region": "BC y BCS (Costa Occidental III)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-05-31",
    "fechaTermino1": "2025-11-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5718993&fecha=15/05/2024",
    "fechaPublicacion": "15/05/2024",
    "nombreAcuerdo": "ACUERDO por el que se establece la veda de langosta en la zona III"
  },
  {
    "id": "96",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta verde",
    "nombreCientifico": "Panulirus gracilis",
    "region": "BC y BCS (Costa Occidental III)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-05-31",
    "fechaTermino1": "2025-11-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5718993&fecha=15/05/2024",
    "fechaPublicacion": "15/05/2024",
    "nombreAcuerdo": "ACUERDO por el que se establece la veda de langosta en la zona III"
  },
  {
    "id": "97",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta roja",
    "nombreCientifico": "Panulirus interruptus",
    "region": "BC y BCS (Costa Occidental III)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-05-31",
    "fechaTermino1": "2025-11-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5718993&fecha=15/05/2024",
    "fechaPublicacion": "15/05/2024",
    "nombreAcuerdo": "ACUERDO por el que se establece la veda de langosta en la zona III"
  },
  {
    "id": "98",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta azul",
    "nombreCientifico": "Panulirus inflatus",
    "region": "Golfo California-Pacífico (Zona IV)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-01",
    "fechaTermino1": "2025-10-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5096857&fecha=31/08/2005",
    "fechaPublicacion": "31/08/2005",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para langosta"
  },
  {
    "id": "99",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta verde",
    "nombreCientifico": "Panulirus gracilis",
    "region": "Golfo California-Pacífico (Zona IV)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-01",
    "fechaTermino1": "2025-10-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5096857&fecha=31/08/2005",
    "fechaPublicacion": "31/08/2005",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para langosta"
  },
  {
    "id": "100",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta roja",
    "nombreCientifico": "Panulirus interruptus",
    "region": "Golfo California-Pacífico (Zona IV)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-01",
    "fechaTermino1": "2025-10-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5096857&fecha=31/08/2005",
    "fechaPublicacion": "31/08/2005",
    "nombreAcuerdo": "ACUERDO por el que se establece veda temporal para langosta"
  },
  {
    "id": "101",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta del caribe",
    "nombreCientifico": "Panulirus argus",
    "region": "Golfo México (Zona V)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2026-03-01",
    "fechaTermino1": "2026-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "102",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta pinta",
    "nombreCientifico": "Panulirus guttatus",
    "region": "Golfo México (Zona V)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2026-03-01",
    "fechaTermino1": "2026-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "103",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langosta verde",
    "nombreCientifico": "Panulirus laevicauda",
    "region": "Golfo México (Zona V)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2026-03-01",
    "fechaTermino1": "2026-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "104",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langostino",
    "nombreCientifico": "Macrobrachium americanum",
    "region": "Pacífico (Aguas continentales)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-08-01",
    "fechaTermino1": "2025-10-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5135886&fecha=31/03/2010",
    "fechaPublicacion": "31/03/2010",
    "nombreAcuerdo": "ACUERDO por el que se establece veda para especies de aguas continentales"
  },
  {
    "id": "105",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Langostino",
    "nombreCientifico": "Macrobrachium tenellum",
    "region": "Pacífico (Aguas continentales)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-08-01",
    "fechaTermino1": "2025-10-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5135886&fecha=31/03/2010",
    "fechaPublicacion": "31/03/2010",
    "nombreAcuerdo": "ACUERDO por el que se establece veda para especies de aguas continentales"
  },
  {
    "id": "106",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Lisa",
    "nombreCientifico": "Mugil cephalus",
    "region": "BC, BCS, Sonora, Sinaloa, Nayarit, Jalisco (Litoral)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-12-01",
    "fechaTermino1": "2026-01-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "107",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Lisa",
    "nombreCientifico": "Mugil cephalus",
    "region": "Colima, Michoacán, Guerrero, Oaxaca, Chiapas (Litoral)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-11-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4868359&fecha=16/03/1994",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "108",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Lisa",
    "nombreCientifico": "Mugil cephalus",
    "region": "Tamaulipas, Veracruz norte (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-12-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "2026-02-01",
    "fechaTermino2": "2026-02-28",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5411228&fecha=16/10/2015",
    "fechaPublicacion": "16/10/2015",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda para lisa y liseta"
  },
  {
    "id": "109",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Lisa",
    "nombreCientifico": "Mugil cephalus",
    "region": "Laguna Madre, Tamaulipas",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-09-01",
    "fechaTermino1": "2025-11-10",
    "fechaInicio2": "2025-12-01",
    "fechaTermino2": "2025-12-30",
    "fechaInicio3": "2026-02-01",
    "fechaTermino3": "2026-02-28",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5411228&fecha=16/10/2015",
    "fechaPublicacion": "16/10/2015",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda para lisa y liseta"
  },
  {
    "id": "110",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Liseta",
    "nombreCientifico": "Mugil curema",
    "region": "BC, BCS, Sonora, Sinaloa, Nayarit, Jalisco (Litoral)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-04-01",
    "fechaTermino1": "2025-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4678590&fecha=16/03/1994#gsc.tab=0",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "111",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Liseta",
    "nombreCientifico": "Mugil curema",
    "region": "Colima, Michoacán, Guerrero, Oaxaca, Chiapas (Litoral)",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-05-15",
    "fechaTermino1": "2025-07-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4678590&fecha=16/03/1994#gsc.tab=0",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "112",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Liseta",
    "nombreCientifico": "Mugil curema",
    "region": "Tamaulipas, Veracruz norte (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-12-01",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "2026-02-01",
    "fechaTermino2": "2026-02-28",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4678590&fecha=16/03/1994#gsc.tab=0",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "113",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Liseta",
    "nombreCientifico": "Mugil curema",
    "region": "Laguna Madre, Tamaulipas",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-09-01",
    "fechaTermino1": "2025-11-10",
    "fechaInicio2": "2025-12-01",
    "fechaTermino2": "2025-12-30",
    "fechaInicio3": "2026-02-01",
    "fechaTermino3": "2026-02-28",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5411876&fecha=16/10/2015#gsc.tab=0",
    "fechaPublicacion": "16/10/2015",
    "nombreAcuerdo": "ACUERDO por el que se modifica el aviso de vedas para lisa y liseta en la Laguna Madre, Tamaulipas"
  },
  {
    "id": "114",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Lobina",
    "nombreCientifico": "Micropterus salmoides",
    "region": "Chihuahua (Embalses)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2026-03-10",
    "fechaTermino1": "2026-06-25",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5137177&fecha=31/03/2010",
    "fechaPublicacion": "31/03/2010",
    "nombreAcuerdo": "ACUERDO por el que se establecen vedas para especies en aguas continentales"
  },
  {
    "id": "115",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Lobina",
    "nombreCientifico": "Micropterus salmoides",
    "region": "Aguamilpa y El Cajón, Nayarit",
    "zona": "Aguas continentales",
    "fechaInicio1": "2026-03-01",
    "fechaTermino1": "2026-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5137177&fecha=31/03/2010",
    "fechaPublicacion": "31/03/2010",
    "nombreAcuerdo": "ACUERDO por el que se establecen vedas para especies en aguas continentales"
  },
  {
    "id": "116",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Lobina",
    "nombreCientifico": "Micropterus salmoides",
    "region": "Presa Zimapán, Hidalgo y Querétaro",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-04-21",
    "fechaTermino1": "2025-06-20",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5292054&fecha=13/03/2013#gsc.tab=0",
    "fechaPublicacion": "13/03/2013",
    "nombreAcuerdo": "ACUERDO por el que se modifica el periodo de veda en la presa Zimapán"
  },
  {
    "id": "117",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Mero",
    "nombreCientifico": "Epinephelus morio",
    "region": "Tabasco, Campeche, Yucatán, Quintana Roo",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2026-02-01",
    "fechaTermino1": "2026-03-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5475258&fecha=03/03/2017",
    "fechaPublicacion": "03/03/2017",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda para especies de mero en el Golfo de México"
  },
  {
    "id": "118",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Ostión de placer",
    "nombreCientifico": "Crassostrea corteziensis",
    "region": "Golfo California-Pacífico",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-15",
    "fechaTermino1": "2025-11-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5323870&fecha=29/11/2013#gsc.tab=0",
    "fechaPublicacion": "29/11/2013",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda del ostión de placer en el Pacífico"
  },
  {
    "id": "119",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Ostión de placer",
    "nombreCientifico": "Crassostrea corteziensis",
    "region": "Sur Teacapán, Sinaloa",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-07-15",
    "fechaTermino1": "2026-02-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5323870&fecha=29/11/2013#gsc.tab=0",
    "fechaPublicacion": "29/11/2013",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda del ostión de placer en el Pacífico"
  },
  {
    "id": "120",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Ostión de roca",
    "nombreCientifico": "Crassostrea iridescens",
    "region": "Sinaloa-Chiapas",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-06-01",
    "fechaTermino1": "2025-08-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5704435&fecha=10/10/2023#gsc.tab=0",
    "fechaPublicacion": "10/10/2023",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda del ostión de roca en el Pacífico"
  },
  {
    "id": "121",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Ostión",
    "nombreCientifico": "Crassostrea virginica",
    "region": "Tabasco (Sistemas Lagunares)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-04-15",
    "fechaTermino1": "2025-05-31",
    "fechaInicio2": "2025-09-15",
    "fechaTermino2": "2025-10-31",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5087616&fecha=20/04/2009",
    "fechaPublicacion": "20/04/2009",
    "nombreAcuerdo": "ACUERDO por el que se establece veda para la pesca comercial de ostión (Crassostrea virginica) en las aguas de jurisdicción federal en el Estado de Tabasco."
  },
  {
    "id": "122",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Pescado blanco",
    "nombreCientifico": "Chirostoma sphyraena",
    "region": "Lago Chapala, Jalisco y Michoacán",
    "zona": "Aguas continentales",
    "fechaInicio1": "2026-02-01",
    "fechaTermino1": "2026-03-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5137177&fecha=31/03/2010",
    "fechaPublicacion": "31/03/2010",
    "nombreAcuerdo": "ACUERDO por el que se establecen épocas y zonas de veda para la pesca de diferentes especies de la fauna acuática en aguas continentales de jurisdicción federal de los Estados Unidos Mexicanos."
  },
  {
    "id": "123",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Pulpo maya",
    "nombreCientifico": "Octopus maya",
    "region": "Campeche, Yucatán, Quintana Roo (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-12-16",
    "fechaTermino1": "2026-07-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4678590&fecha=16/03/1994#gsc.tab=0",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "124",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Pulpo común",
    "nombreCientifico": "Octopus vulgaris",
    "region": "Campeche, Yucatán, Quintana Roo (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-12-16",
    "fechaTermino1": "2026-07-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4678590&fecha=16/03/1994#gsc.tab=0",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "125",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Pulpo común",
    "nombreCientifico": "Octopus vulgaris",
    "region": "Sistema Arrecifal Veracruzano, Veracruz",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-01-01",
    "fechaTermino1": "2025-02-28",
    "fechaInicio2": "2025-08-01",
    "fechaTermino2": "2025-08-30",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5253633&fecha=11/06/2012#gsc.tab=0",
    "fechaPublicacion": "11/06/2012",
    "nombreAcuerdo": "ACUERDO por el que se modifica el Aviso para establecer los periodos de veda de pulpo en el Sistema Arrecifal Veracruzano"
  },
  {
    "id": "126",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Pulpo café",
    "nombreCientifico": "Octopus bimaculatus",
    "region": "Bahía de los Ángeles, BC",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-08-01",
    "fechaTermino1": "2025-11-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5503748&fecha=07/11/2017",
    "fechaPublicacion": "07/11/2017",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda temporal y tallas mínimas para pulpo en Bahía de los Ángeles"
  },
  {
    "id": "127",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Pulpo verde",
    "nombreCientifico": "Octopus hubbsorum",
    "region": "Bahía de los Ángeles, BC",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-09-01",
    "fechaTermino1": "2025-11-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5503748&fecha=07/11/2017",
    "fechaPublicacion": "07/11/2017",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda temporal y tallas mínimas para pulpo en Bahía de los Ángeles"
  },
  {
    "id": "128",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Rayas",
    "nombreCientifico": "Todas las especies",
    "region": "Océano Pacífico",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-07-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5307611&fecha=23/07/2013",
    "fechaPublicacion": "23/07/2013",
    "nombreAcuerdo": "ACUERDO por el que se modifica el aviso para concluir el periodo de veda de tiburones y rayas en el Océano Pacífico"
  },
  {
    "id": "129",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Robalo",
    "nombreCientifico": "Centropomus sp",
    "region": "Soto la Marina-Chachalacas, Tamaulipas-Veracruz",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-05-15",
    "fechaTermino1": "2025-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4678590&fecha=16/03/1994#gsc.tab=0",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "130",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Robalo",
    "nombreCientifico": "Centropomus sp",
    "region": "Chachalacas-Tonalá, Veracruz-Tabasco",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-07-01",
    "fechaTermino1": "2025-08-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=4678590&fecha=16/03/1994#gsc.tab=0",
    "fechaPublicacion": "16/03/1994",
    "nombreAcuerdo": "AVISO por el que se da a conocer el establecimiento de épocas y zonas de veda"
  },
  {
    "id": "131",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Tiburones",
    "nombreCientifico": "Todas excepto permanentes",
    "region": "Tamaulipas, Veracruz, Quintana Roo (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5344735&fecha=15/05/2014#gsc.tab=0",
    "fechaPublicacion": "15/05/2014",
    "nombreAcuerdo": "ACUERDO por el que se modifica el periodo y zonas de veda de tiburones en el Golfo de México y Mar Caribe"
  },
  {
    "id": "132",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Tiburones",
    "nombreCientifico": "Todas excepto permanentes",
    "region": "Tabasco, Campeche, Yucatán (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-05-15",
    "fechaTermino1": "2025-06-15",
    "fechaInicio2": "2025-08-01",
    "fechaTermino2": "2025-08-30",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5344735&fecha=15/05/2014#gsc.tab=0",
    "fechaPublicacion": "15/05/2014",
    "nombreAcuerdo": "ACUERDO por el que se modifica el periodo y zonas de veda de tiburones en el Golfo de México y Mar Caribe"
  },
  {
    "id": "133",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Tiburones",
    "nombreCientifico": "Todas excepto permanentes",
    "region": "Océano Pacífico",
    "zona": "Océano Pacífico",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-07-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5307611&fecha=23/07/2013#gsc.tab=0",
    "fechaPublicacion": "23/07/2013",
    "nombreAcuerdo": "ACUERDO por el que se modifica el aviso de veda para tiburones y rayas en el Océano Pacífico"
  },
  {
    "id": "134",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Tilapia",
    "nombreCientifico": "Oreochromis sp",
    "region": "Laguna de Amela, Colima",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-07-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5432311&fecha=07/04/2016#gsc.tab=0",
    "fechaPublicacion": "07/04/2016",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda para la captura de Tilapia en la Laguna de Amela, Colima"
  },
  {
    "id": "135",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Tilapia",
    "nombreCientifico": "Oreochromis spp",
    "region": "Presa Santa Rosa, Jalisco",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-07-01",
    "fechaTermino1": "2025-08-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5555326&fecha=27/03/2019#gsc.tab=0",
    "fechaPublicacion": "27/03/2019",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda para la captura de tilapia en la Presa Santa Rosa, Jalisco"
  },
  {
    "id": "136",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Tilapia",
    "nombreCientifico": "Oreochromis aureus",
    "region": "Presa El Infiernillo, Michoacán-Guerrero",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-07-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5444032&fecha=08/07/2016#gsc.tab=0",
    "fechaPublicacion": "08/07/2016",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda para la captura de tilapia en la presa El Infiernillo"
  },
  {
    "id": "137",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Tilapia",
    "nombreCientifico": "Oreochromis mossambicus",
    "region": "Presa El Infiernillo, Michoacán-Guerrero",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-07-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5444032&fecha=08/07/2016#gsc.tab=0",
    "fechaPublicacion": "08/07/2016",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda para la captura de tilapia en la presa El Infiernillo"
  },
  {
    "id": "138",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Tilapia",
    "nombreCientifico": "Tilapia rendalli",
    "region": "Presa El Infiernillo, Michoacán-Guerrero",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-07-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5444032&fecha=08/07/2016#gsc.tab=0",
    "fechaPublicacion": "08/07/2016",
    "nombreAcuerdo": "ACUERDO por el que se modifica la veda para la captura de tilapia en la presa El Infiernillo"
  },
  {
    "id": "139",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Todas las especies peces",
    "nombreCientifico": "Todas",
    "region": "Presa Zimapán, Hidalgo-Querétaro",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-04-21",
    "fechaTermino1": "2025-06-20",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5292054&fecha=13/03/2013#gsc.tab=0",
    "fechaPublicacion": "13/03/2013",
    "nombreAcuerdo": "ACUERDO por el que se establece veda para todas las especies de peces en la Presa Zimapán"
  },
  {
    "id": "140",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Todas las especies peces",
    "nombreCientifico": "Todas",
    "region": "Aguamilpa-El Cajón, Nayarit",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-03-01",
    "fechaTermino1": "2025-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5137177&fecha=31/03/2010#gsc.tab=0",
    "fechaPublicacion": "31/03/10",
    "nombreAcuerdo": "ACUERDO por el que se establecen épocas y zonas de veda para la pesca de diferentes especies de la fauna acuática en aguas continentales de jurisdicción federal de los Estados Unidos Mexicanos."
  },
  {
    "id": "141",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Todas las especies peces",
    "nombreCientifico": "Todas",
    "region": "Presa Melchor Ocampo, Michoacán",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-07-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5530222&fecha=05/07/2018#gsc.tab=0",
    "fechaPublicacion": "05/07/18",
    "nombreAcuerdo": "ACUERDO por el que se modifica el similar por el que se establecen épocas y zonas de veda para la pesca de diferentes especies de la fauna acuática en aguas continentales de jurisdicción federal de los Estados Unidos Mexicanos, publicado el 31 de marzo de 2010, con el fin de establecer el periodo de veda para la captura de todas las especies de peces existentes en la Laguna de Yuriria, Guanajuato."
  },
  {
    "id": "142",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Todas las especies peces",
    "nombreCientifico": "Todas",
    "region": "Laguna de Yuriria, Guanajuato",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-04-01",
    "fechaTermino1": "2025-06-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5559139&fecha=02/05/2019#gsc.tab=0",
    "fechaPublicacion": "02/05/19",
    "nombreAcuerdo": "ACUERDO por el que se modifica el similar por el que se establecen épocas y zonas de veda para la pesca de diferentes especies de la fauna acuática en aguas continentales de jurisdicción federal de los Estados Unidos Mexicanos, publicado el 31 de marzo de 2010, con el fin de establecer el periodo de veda para la captura de todas las especies de peces existentes en el embalse de la Presa Melchor Ocampo, Michoacán."
  },
  {
    "id": "143",
    "tipoVeda": "Temporal Fija",
    "pesqueria": "Todas las especies peces",
    "nombreCientifico": "Todas",
    "region": "Dique La Primavera, Sinaloa",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-08-01",
    "fechaTermino1": "2025-09-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5566698&fecha=29/07/2019#gsc.tab=0",
    "fechaPublicacion": "29/07/19",
    "nombreAcuerdo": "ACUERDO por el que se modifica el similar por el que se establecen épocas y zonas de veda para la pesca de diferentes especies de la fauna acuática en aguas continentales de jurisdicción federal de los Estados Unidos Mexicanos, publicado el 31 de marzo de 2010, con el fin de establecer el periodo de veda temporal y la zona de veda permanente para la captura de todas las especies de peces existentes en el Dique La Primavera, Sinaloa."
  },
  {
    "id": "144",
    "tipoVeda": "Temporal Variable",
    "pesqueria": "Camarón del Pacífico",
    "nombreCientifico": "Todas especies peneidos",
    "region": "BCS, Nayarit, Sinaloa, Sonora (Sistemas lagunares)",
    "zona": "Aguas continentales",
    "fechaInicio1": "2025-03-20",
    "fechaTermino1": "2025-12-31",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5715468&fecha=14/03/2024",
    "fechaPublicacion": "14/03/24",
    "nombreAcuerdo": "ACUERDO por el que se establece el inicio de la veda temporal para camarón del Pacífico"
  },
  {
    "id": "145",
    "tipoVeda": "Temporal Variable",
    "pesqueria": "Camarón Golfo México",
    "nombreCientifico": "Todas especies peneidos",
    "region": "Tamaulipas-Veracruz (Litoral)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-08-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5718075&fecha=30/04/2024",
    "fechaPublicacion": "30/04/24",
    "nombreAcuerdo": "ACUERDO por el que se establece la veda temporal para camarón del Golfo de México y Mar Caribe"
  },
  {
    "id": "146",
    "tipoVeda": "Temporal Variable",
    "pesqueria": "Camarón Golfo México",
    "nombreCientifico": "Todas especies peneidos",
    "region": "Campeche-Tabasco (Franja costera)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-06-01",
    "fechaTermino1": "2025-08-15",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Inactiva",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5718075&fecha=30/04/2024",
    "fechaPublicacion": "30/04/24",
    "nombreAcuerdo": "ACUERDO por el que se establece la veda temporal para camarón del Golfo de México y Mar Caribe"
  },
  {
    "id": "147",
    "tipoVeda": "Temporal Variable",
    "pesqueria": "Camarón siete barbas",
    "nombreCientifico": "Todas especies peneidos",
    "region": "Campeche-Tabasco (Franja costera)",
    "zona": "Golfo de México y Mar Caribe",
    "fechaInicio1": "2025-05-01",
    "fechaTermino1": "2025-09-30",
    "fechaInicio2": "",
    "fechaTermino2": "",
    "fechaInicio3": "",
    "fechaTermino3": "",
    "status": "Activa",
    "enlaceDOF": "https://www.dof.gob.mx/nota_detalle.php?codigo=5718075&fecha=30/04/2024",
    "fechaPublicacion": "30/04/24",
    "nombreAcuerdo": "ACUERDO por el que se establece la veda temporal para camarón del Golfo de México y Mar Caribe"
  }
]


export const getUniqueRegions = (): string[] => {
  const regions = vedasData.map((veda) => veda.region)
  return Array.from(new Set(regions)).sort()
}

export const getUniqueFisheries = (): string[] => {
  const fisheries = vedasData.map((veda) => veda.pesqueria)
  return Array.from(new Set(fisheries)).sort()
}

export const getUniqueVedaTypes = (): string[] => {
  const types = vedasData.map((veda) => veda.tipoVeda)
  return Array.from(new Set(types)).sort()
}

// Helper function to format ISO date to DD/MM format
export const formatDateToDDMM = (dateStr: string): string => {
  if (!dateStr || dateStr === "Todo el año" || dateStr === "Por definir") return dateStr
  
  try {
    const date = new Date(dateStr)
    if (isNaN(date.getTime())) return dateStr
    
    const day = date.getDate().toString().padStart(2, '0')
    const month = (date.getMonth() + 1).toString().padStart(2, '0')
    return `${day}/${month}`
  } catch {
    return dateStr
  }
}

export const isVedaActive = (veda: VedaData): boolean => {
  if (veda.tipoVeda === "Permanente") return true

  const today = new Date()
  const currentYear = today.getFullYear()

  // Parse ISO date strings (YYYY-MM-DD)
  const parseISODate = (dateStr: string) => {
    if (!dateStr || dateStr === "Todo el año" || dateStr === "Por definir") return null
    
    try {
      const date = new Date(dateStr)
      return {
        year: date.getFullYear(),
        month: date.getMonth() + 1,
        day: date.getDate()
      }
    } catch {
      return null
    }
  }

  const start1 = parseISODate(veda.fechaInicio1)
  const end1 = parseISODate(veda.fechaTermino1)

  if (!start1 || !end1) return false

  // Check if current date is within the veda period
  const isInPeriod = (start: { year: number; month: number; day: number }, end: { year: number; month: number; day: number }) => {
    const startDate = new Date(start.year, start.month - 1, start.day)
    const endDate = new Date(end.year, end.month - 1, end.day)
    
    return today >= startDate && today <= endDate
  }

  let active = isInPeriod(start1, end1)

  // Check second period if exists
  if (veda.fechaInicio2 && veda.fechaTermino2) {
    const start2 = parseISODate(veda.fechaInicio2)
    const end2 = parseISODate(veda.fechaTermino2)
    if (start2 && end2) {
      active = active || isInPeriod(start2, end2)
    }
  }

  // Check third period if exists
  if (veda.fechaInicio3 && veda.fechaTermino3) {
    const start3 = parseISODate(veda.fechaInicio3)
    const end3 = parseISODate(veda.fechaTermino3)
    if (start3 && end3) {
      active = active || isInPeriod(start3, end3)
    }
  }

  return active
}

// Export alias for compatibility
export const vedas = vedasData
